spring:
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 9090
  servlet:
    context-path: /auth
user:
  oauth:
    clientId: R2dpxQ3vPrtfgF72
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: http://localhost:9090/login/oauth2/code/
    user.username: Andrew
    user.password: abcd