server:
  port: 9090
spring:
  application:
    name: config-server
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IBRAH1M/spring-sso/tree/{label}/configs/{application}