spring:
  application:
    name: config-discovery-service
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: http://www.github.com/spring-sso/configs/{application}
        bootstrap: true
        prefix: /configurations
